# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://methuselah-0.github.io/awesomelib/"

git_url = "https://github.com/methuselah-0/awesomelib/tree/master/"

def custom_doc_links(name): return None
